server:
  port: 8070

application:
  version: AppVersion 1.0.0
  title: thejoeun company

spring:
  sql:
    init:
      mode: always
      #always: embeded db가 아닌 외부 db 사용시 스프링부트를 실행할 때마다 data.sql schema.sql import.sql을 항상 실행
      #never: data.sql schema.sql import.sql을 실행하지 않음
      encoding: utf-8
  datasource:
    url: jdbc:mariadb://localhost:3306/mydb
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
#  url: jdbc:h2:mem:testdb     # H2 Embeded Memory
#  driver-class-name: org.h2.Driver # H2 connect driver
#  username: sa
#  password:

  h2:
    console:
      path: /h2-console
      enabled: true
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true #사용하는 sql model comment 주석이 생김
    generate-ddl: true #true / false
    hibernate:
       ddl-auto: create
      #create : spring boot 처음 실행시에 Entity로 된 클래스 및 테이블을 drop하고 create함.
      #create-drop: spring boot 처음 실행시에 Entity로 된 클래스 및 테이블을 drop하고 create하고 springboot 종료시에 다시 drop.
      #update: 연결된 db schema와 자바 entity와 비교를 하여 다른 게 있다면 다른것만 ddl 코드를 생성.
      #validate: ddl 구문을 만들지 않고 연결된 db schema와 자바 entity와 비교하여 다른 게 있다면 오류코드만 보여줌
      #none: ddl구문을 만들지 않음.
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  devtools:
    livereload:
      enabled: true

  logging:
    level:
      org:
        hibernate:
          orm:
            jdbc:
              bind: trace
#          SQL: debug
#          type: trace
#           type:
#             descriptor:
#               sql: trace
#      root: trace